Did 3rd homework
QuantuM1o1/TinkoffHomeworks pull request #4
Opened 2023-10-25 14:25 UTC by QuantuM1o1

2023-10-31 21:40 UTC, ZhekTheDark requested changes

2023-10-31 21:40 UTC, ZhekTheDark commented on src/main/java/edu/hw3/Task3.java
> +            if (map.containsKey(o)) {
можно сделать `map.put(o, map.getOrDefault(o, 0) + 1);`

2023-10-31 21:40 UTC, ZhekTheDark commented on src/main/java/edu/hw3/Task3.java
> +        HashMap<Object, Integer> map = new HashMap<>();
Map<Object, Integer> map = new HashMap<>();

2023-11-03 10:52 UTC, QuantuM1o1 commented
Исправил

2023-11-13 06:24 UTC, merged