Project 2
QuantuM1o1/TinkoffHomeworks pull request #5
Opened 2023-10-31 07:03 UTC by QuantuM1o1

2023-11-15 23:58 UTC, VictorMinsky requested changes
Добавь меня, пожалуйста, в контрибьюторы репозитория, чтобы я мог резолвить треды с замечаниями.

Гайд -- https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-access-to-your-personal-repositories/inviting-collaborators-to-a-personal-repository

2023-11-15 23:58 UTC, VictorMinsky commented on src/main/java/edu/project2/AldousBroderGenerator.java
У тебя неправильно настроен бейдж в README.md в корне проекта, ссылка ведёт на исходную репу преподавателя

2023-11-15 23:58 UTC, VictorMinsky commented on src/main/java/edu/project2/AldousBroderGenerator.java
> +        {new Coordinate(0, -1), new Coordinate(1, 0), new Coordinate(0, 1), new Coordinate(-1, 0)};
Дублируешь в RecursiveBacktrackerGenerator, вынеси общий код

2023-11-15 23:58 UTC, VictorMinsky commented on src/main/java/edu/project2/AldousBroderGenerator.java
> +            ArrayList<Integer> nearbyCells = new ArrayList<>();
Слева надо указывать интерфейс List

2023-11-15 23:58 UTC, VictorMinsky commented on src/main/java/edu/project2/AldousBroderGenerator.java
> +            }
Тоже дублируешь логику, вынеси общий код

2023-11-15 23:58 UTC, VictorMinsky commented on src/main/java/edu/project2/BFSSolver.java
> +        }
Дублируешь логику с dfs, вынеси общий код

2023-11-16 14:12 UTC, QuantuM1o1 commented on src/main/java/edu/project2/AldousBroderGenerator.java
> +            }
@VictorMinsky Там в одном случае if внутри if, а в другом просто if. Не особо понимаю, как это можно вынести

2023-11-16 21:29 UTC, VictorMinsky commented on src/main/java/edu/project2/AldousBroderGenerator.java
> +            }
Это практически нулевая разница, в остальном функции близки к 1 в 1. Можете реализовать это через добавление в функцию коллбека

2023-11-19 21:19 UTC, VictorMinsky approved these changes
OK

2023-11-19 21:19 UTC, VictorMinsky commented on src/main/java/edu/project2/AldousBroderGenerator.java
Неправильно поменял. Тебе надо было сделать ссылку `https://github.com/QuantuM1o1/TinkoffHomeworks/actions/workflows/build.yml/badge.svg`

2023-11-20 04:46 UTC, merged